version: '3.0'

services:

  datastorage:
    image: postgres
    restart: always
    container_name: datastorage_container
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./containers/lib/postgresql/data/:/var/lib/postgresql/data/

  db_padmin:
    image: dpage/pgadmin4
    container_name: db_padmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@cocotrading.io
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "81:80"
    volumes:
      - ./containers/lib/pgadmin/:/var/lib/pgadmin/
